package GreetingsApp;


/**
* GreetingsApp/GreetingsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Greetings.idl
* Monday, December 2, 2013 4:15:42 AM CST
*/

abstract public class GreetingsHelper
{
  private static String  _id = "IDL:GreetingsApp/Greetings:1.0";

  public static void insert (org.omg.CORBA.Any a, GreetingsApp.Greetings that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static GreetingsApp.Greetings extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (GreetingsApp.GreetingsHelper.id (), "Greetings");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static GreetingsApp.Greetings read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GreetingsStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, GreetingsApp.Greetings value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static GreetingsApp.Greetings narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GreetingsApp.Greetings)
      return (GreetingsApp.Greetings)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      GreetingsApp._GreetingsStub stub = new GreetingsApp._GreetingsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static GreetingsApp.Greetings unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GreetingsApp.Greetings)
      return (GreetingsApp.Greetings)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      GreetingsApp._GreetingsStub stub = new GreetingsApp._GreetingsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
