package GreetingsApp;

/**
* GreetingsApp/GreetingsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Greetings.idl
* Monday, December 2, 2013 4:15:42 AM CST
*/

public final class GreetingsHolder implements org.omg.CORBA.portable.Streamable
{
  public GreetingsApp.Greetings value = null;

  public GreetingsHolder ()
  {
  }

  public GreetingsHolder (GreetingsApp.Greetings initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GreetingsApp.GreetingsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GreetingsApp.GreetingsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GreetingsApp.GreetingsHelper.type ();
  }

}
