package GreetingsApp;

/**
* GreetingsApp/GreetingsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Greetings.idl
* Monday, December 2, 2013 4:15:42 AM CST
*/

public interface GreetingsOperations 
{
  String expressGreetings ();
  void shutdown ();
} // interface GreetingsOperations
